"""empty message

Revision ID: 747515ef836d
Revises: 
Create Date: 2025-02-28 18:33:42.413642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747515ef836d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('car_type', sa.String(length=50), nullable=False),
    sa.Column('km_limit_day', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('max_passengers', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('total_km', sa.String(length=50), nullable=False),
    sa.Column('automatic', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('door', sa.String(length=200), nullable=True),
    sa.Column('airport_take', sa.Boolean(), nullable=False),
    sa.Column('air', sa.Boolean(), nullable=False),
    sa.Column('punctuation', sa.Integer(), nullable=False),
    sa.Column('guarantee', sa.Boolean(), nullable=False),
    sa.Column('insurance', sa.Boolean(), nullable=False),
    sa.Column('info', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excursiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('lunch', sa.Boolean(), nullable=False),
    sa.Column('excursion_type', sa.String(length=50), nullable=False),
    sa.Column('transport', sa.String(length=50), nullable=False),
    sa.Column('max_people', sa.String(length=50), nullable=False),
    sa.Column('childs', sa.Boolean(), nullable=False),
    sa.Column('health_problems', sa.String(length=50), nullable=False),
    sa.Column('info', sa.String(length=5000), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('punctuation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hoteles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Integer(), nullable=False),
    sa.Column('check_out', sa.Integer(), nullable=False),
    sa.Column('pension', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('pool', sa.Boolean(), nullable=False),
    sa.Column('sports', sa.Boolean(), nullable=False),
    sa.Column('events', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Hotels', 'Flys', 'Excursions', 'Cars', name='favoritetypeenum'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.create_table('vuelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('punctuation', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('land', sa.String(length=50), nullable=False),
    sa.Column('take_off', sa.String(length=50), nullable=False),
    sa.Column('origin_city', sa.String(length=50), nullable=False),
    sa.Column('destiny_city', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('flight_type', sa.String(length=50), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('baggage', sa.Boolean(), nullable=False),
    sa.Column('baggage_kg', sa.Integer(), nullable=False),
    sa.Column('lunch', sa.Boolean(), nullable=False),
    sa.Column('time_departure', sa.String(), nullable=False),
    sa.Column('time_arrival', sa.String(), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vuelos')
    op.drop_table('follower')
    op.drop_table('favourite')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('hoteles')
    op.drop_table('excursiones')
    op.drop_table('coches')
    # ### end Alembic commands ###
