"""empty message

Revision ID: 803184588a42
Revises: 95032cfeb904
Create Date: 2025-03-02 18:03:01.623420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803184588a42'
down_revision = '95032cfeb904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coches', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('vuelos', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vuelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('coches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
