"""empty message

Revision ID: 95032cfeb904
Revises: 747515ef836d
Create Date: 2025-03-02 17:58:50.015203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95032cfeb904'
down_revision = '747515ef836d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('vuelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vuelos', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('coches', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
