"""empty message

Revision ID: e7d1b51a4a38
Revises: 
Create Date: 2025-02-21 17:42:03.755292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d1b51a4a38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('info', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('VUELO', 'HOTEL', 'EXCURSION', 'COCHE', name='favoritetypeenum'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('favourite_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favourite_list'], ['favourite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('info', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follower',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.create_table('coches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('car_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('excursiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('lunch', sa.Boolean(), nullable=False),
    sa.Column('excursion_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hoteles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Integer(), nullable=False),
    sa.Column('check_out', sa.Integer(), nullable=False),
    sa.Column('pension', sa.Boolean(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('pool', sa.Boolean(), nullable=False),
    sa.Column('sports', sa.Boolean(), nullable=False),
    sa.Column('events', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vuelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('punctuation', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('land', sa.Integer(), nullable=False),
    sa.Column('take_off', sa.Integer(), nullable=False),
    sa.Column('origin_city', sa.Integer(), nullable=False),
    sa.Column('destiny_city', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('flight_type', sa.String(length=50), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('pets', sa.Boolean(), nullable=False),
    sa.Column('baggage', sa.Boolean(), nullable=False),
    sa.Column('baggage_kg', sa.Integer(), nullable=False),
    sa.Column('lunch', sa.Boolean(), nullable=False),
    sa.Column('time_departure', sa.Integer(), nullable=False),
    sa.Column('time_arrival', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destiny_city'], ['city.id'], ),
    sa.ForeignKeyConstraint(['origin_city'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vuelos')
    op.drop_table('hoteles')
    op.drop_table('excursiones')
    op.drop_table('coches')
    op.drop_table('follower')
    op.drop_table('city')
    op.drop_table('user')
    op.drop_table('favourite')
    op.drop_table('country')
    # ### end Alembic commands ###
